"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../../../_components/app-shell";
import { employeeNavItems } from "../../../_components/role-nav";

export default function EmployeeAddMonitorPage() {
  const router = useRouter();
  const [monitorName, setMonitorName] = useState("");
  const [monitorCategory, setMonitorCategory] = useState<"theft-controller" | "elevator">("elevator");
  const [linkedCustomerId, setLinkedCustomerId] = useState("");
  const [customerOptions, setCustomerOptions] = useState<
    Array<{ id: string; fullName: string; customerNumber: string; region: string; boxNumber: string }>
  >([]);
  const [message, setMessage] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    fetch("/api/customers?region=all&status=active")
      .then(async (response) => {
        if (!response.ok) throw new Error("Failed to load customers.");
        const payload = (await response.json()) as {
          customers?: Array<{
            id: string;
            fullName: string;
            customerNumber: string;
            region?: string;
            boxNumber?: string;
          }>;
        };
        setCustomerOptions(
          (payload.customers ?? []).map((customer) => ({
            id: customer.id,
            fullName: customer.fullName,
            customerNumber: customer.customerNumber,
            region: customer.region ?? "-",
            boxNumber: customer.boxNumber ?? "-",
          }))
        );
      })
      .catch(() => setCustomerOptions([]));
  }, []);

  const linkedCustomer = customerOptions.find((customer) => customer.id === linkedCustomerId) ?? null;

  async function onSubmit() {
    if (!monitorName.trim() || !linkedCustomerId) {
      setMessage("Monitor name and linked customer are required.");
      return;
    }
    setIsSubmitting(true);
    setMessage("");
    try {
      const response = await fetch("/api/customers", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fullName: monitorName,
          region: "mrah",
          billingType: "metered",
          status: "active",
          mode: "monitor",
          monitorName,
          monitorCategory,
          linkedCustomerId,
        }),
      });
      const payload = (await response.json()) as { error?: string };
      if (!response.ok) {
        setMessage(payload.error ?? "Failed to create monitor customer.");
        return;
      }
      router.push("/employee/customers");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Unknown error.");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <AppShell title="Add Monitor" subtitle="Create a monitor-linked customer" navItems={employeeNavItems}>
      <Link href="/employee/dashboard" className="back-link">
        ← Back to Dashboard
      </Link>
      <div className="card">
        <div className="filters-grid filters-grid-pro">
          <label>
            Monitor Name
            <input value={monitorName} onChange={(e) => setMonitorName(e.target.value)} placeholder="Building Elevator Monitor" />
          </label>
          <label>
            Linked Customer
            <select value={linkedCustomerId} onChange={(e) => setLinkedCustomerId(e.target.value)}>
              <option value="">Select customer</option>
              {customerOptions.map((customer) => (
                <option key={customer.id} value={customer.id}>
                  {customer.fullName} ({customer.customerNumber})
                </option>
              ))}
            </select>
          </label>
          <label>
            Category
            <select
              value={monitorCategory}
              onChange={(e) => setMonitorCategory(e.target.value as "theft-controller" | "elevator")}
            >
              <option value="elevator">elevator</option>
              <option value="theft-controller">theft-controller</option>
            </select>
          </label>
          <label>
            Region
            <input value={linkedCustomer?.region ?? "-"} readOnly disabled />
          </label>
          <label>
            Box
            <input value={linkedCustomer?.boxNumber ?? "-"} readOnly disabled />
          </label>
        </div>
        <p className="muted" style={{ marginTop: 8 }}>
          Monitor customer number is auto-generated by the system (`M-XXXX`).
        </p>
        {message ? <p className="muted">{message}</p> : null}
        <div className="card-actions-right">
          <button type="button" onClick={onSubmit} disabled={isSubmitting}>
            {isSubmitting ? "Creating..." : "Create Monitor"}
          </button>
        </div>
      </div>
    </AppShell>
  );
}
